# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
supported_minecraft_versions=1.21.11
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.6
loader_version=0.19.3
loom_version=1.16-SNAPSHOT

# Mod Properties
mod_version=1.0.1
maven_group=com.yiyihehe.quickcraft

# Dependencies
fabric_api_version=0.139.4+1.21.11
modmenu_version=17.0.0
malilib_version=0.27.14
litematica_version=0.26.11
fabric_asm_version=2.3
quickshulker_version=3.0.1-1.21.5
conditional_mixin_version=0.6.4
